In [1]:
import torch

In [2]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
x = torch.add(x,y)
print(z)

tensor([[0.9952, 0.7812],
        [0.6375, 0.1456]])
tensor([[0.9113, 0.7737],
        [0.4963, 0.9997]])
tensor([[1.9065, 1.5550],
        [1.1339, 1.1453]])


In [3]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)
print(y)

tensor([[0.8106, 0.1336],
        [0.8936, 0.8426]])


In [4]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x*y
z = torch.mul(x,y)

In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x/y
z = torch.div(x,y)
print(z)

tensor([[0.4885, 1.9564],
        [0.5364, 4.4778]])


In [10]:
x = torch.rand(5,3)
print(x)
print(x[:,0])

tensor([[0.1163, 0.7007, 0.5592],
        [0.0768, 0.0518, 0.7794],
        [0.4938, 0.1336, 0.4802],
        [0.3954, 0.6176, 0.4914],
        [0.3189, 0.9736, 0.0326]])
tensor([0.1163, 0.0768, 0.4938, 0.3954, 0.3189])


In [11]:
print(x[1,:])

tensor([0.0768, 0.0518, 0.7794])


In [12]:
print(x[1,1])

tensor(0.0518)


In [13]:
#Reshaping a tensor
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.6645, 0.3745, 0.7311, 0.2817],
        [0.7771, 0.1237, 0.3729, 0.2231],
        [0.5950, 0.3178, 0.8381, 0.4364],
        [0.8335, 0.2412, 0.9542, 0.6540]])
tensor([0.6645, 0.3745, 0.7311, 0.2817, 0.7771, 0.1237, 0.3729, 0.2231, 0.5950,
        0.3178, 0.8381, 0.4364, 0.8335, 0.2412, 0.9542, 0.6540])


In [14]:
y = x.view(-1,8)
print(y)

tensor([[0.6645, 0.3745, 0.7311, 0.2817, 0.7771, 0.1237, 0.3729, 0.2231],
        [0.5950, 0.3178, 0.8381, 0.4364, 0.8335, 0.2412, 0.9542, 0.6540]])


In [15]:
print(y.size())

torch.Size([2, 8])


In [16]:
#Converting numpy to tensor and vice versa
import numpy as np
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [18]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [19]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)

[1. 1. 1. 1. 1.]


In [21]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device=device)
    z = x + y